//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System;

    public partial class Download
    {
        public string FileNameID { get; set; }
        public Nullable<int> Downloads { get; set; }
        public string Date { get; set; }
    }
}
