//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magnets
    {
        public string ProdId { get; set; }
        public string ProdPicture { get; set; }
        public decimal ProdPrice { get; set; }
        public int ProdQty { get; set; }
        public string Catagory { get; set; }
        public string ProdName { get; set; }
        public string Capital { get; set; }
        public string Statehood { get; set; }
    }
}
