//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System.Collections.Generic;

    public partial class Sleeve_Lookup
    {
        public Sleeve_Lookup()
        {
            this.Clothing = new HashSet<Clothing>();
        }
    
        public string SleeveID { get; set; }
        public string Sleeve_Length { get; set; }
    
        public virtual ICollection<Clothing> Clothing { get; set; }
    }
}
