//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaDaaTieDyeTPCEntities : DbContext
    {
        public TaDaaTieDyeTPCEntities()
            : base("name=TaDaaTieDyeTPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cart> Cart { get; set; }
        public DbSet<Catagory_Lookup> Catagory_Lookup { get; set; }
        public DbSet<Clothing> Clothing { get; set; }
        public DbSet<Magnets> Magnets { get; set; }
        public DbSet<Role_Lookup> Role_Lookup { get; set; }
        public DbSet<Size_Lookup> Size_Lookup { get; set; }
        public DbSet<Sleeve_Lookup> Sleeve_Lookup { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Download> Downloads { get; set; }
    }
}
